/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_ipride_License */

#ifndef _Included_jp_co_ipride_License
#define _Included_jp_co_ipride_License
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_ipride_License
 * Method:    isValidFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_co_ipride_License_isValidFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     jp_co_ipride_License
 * Method:    getSubject
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_co_ipride_License_getSubject
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_co_ipride_License
 * Method:    getAppVersion
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_co_ipride_License_getAppVersion
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_co_ipride_License
 * Method:    getStartDate
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_co_ipride_License_getStartDate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_co_ipride_License
 * Method:    getEndDate
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_co_ipride_License_getEndDate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_co_ipride_License
 * Method:    getPublicKey
 * Signature: (Ljava/lang/String;)
 */
JNIEXPORT jbyteArray JNICALL Java_jp_co_ipride_License_getPublicKey
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
